#!/bin/bash
# NABU setup script

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  NABU Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

if [ -f "$CONFIG_FILE" ]; then
    echo "✓ Config already exists at $CONFIG_FILE"
    echo "  Delete it and re-run setup to reconfigure."
    echo ""
else
    read -rp "Home Assistant URL [http://localhost:8123]: " ha_url
    ha_url="${ha_url:-http://localhost:8123}"

    read -rp "HA Long-lived Access Token: " ha_token

    read -rp "Conversation Agent ID: " agent_id

    read -rp "Default language [de]: " lang
    lang="${lang:-de}"

    echo ""
    echo "Conversation ID (for session continuity)."
    echo "  - nabu --show-id shows the current ID on the host"
    echo "  - Leave empty to start a new conversation"
    read -rp "Conversation ID (optional): " conv_id

    cat > "$CONFIG_FILE" << EOF
# NABU Configuration (generated by setup.sh)
HA_URL="${ha_url}"
HA_TOKEN="${ha_token}"
AGENT_ID="${agent_id}"
DEFAULT_LANGUAGE="${lang}"
CONVERSATION_ID="${conv_id}"
EOF

    echo ""
    echo "✓ Config saved to $CONFIG_FILE (git-ignored)"
fi

echo ""
echo "Installing scripts to /usr/local/bin ..."

# Install nabu with absolute config path baked in
NABU_TMP="$(mktemp)"
sed "s|NABU_CONFIG:-\$SCRIPT_DIR/config|NABU_CONFIG:-$CONFIG_FILE|" "$SCRIPT_DIR/nabu" > "$NABU_TMP"

sudo cp "$NABU_TMP" /usr/local/bin/nabu && sudo chmod +x /usr/local/bin/nabu
rm -f "$NABU_TMP"
echo "✓ nabu → /usr/local/bin/nabu"

sudo cp "$SCRIPT_DIR/worker" /usr/local/bin/worker && sudo chmod +x /usr/local/bin/worker
echo "✓ worker → /usr/local/bin/worker"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Done!"
echo ""
echo "  nabu \"Hallo\""
echo "  nabu --show-id"
echo "  nabu --reset"
echo "  worker"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
