#!/bin/bash
# NABU setup script

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  NABU Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

if [ -f "$CONFIG_FILE" ]; then
    echo "✓ Config already exists at $CONFIG_FILE"
    echo "  Delete it and re-run setup to reconfigure."
    echo ""
else
    echo "Configure connection to claude-chat-service:"
    echo ""

    read -rp "Claude Chat Service URL [http://localhost:8765]: " chat_url
    chat_url="${chat_url:-http://localhost:8765}"

    echo ""
    echo "Session ID for conversation continuity."
    echo "  - Get from running service: curl ${chat_url}/health"
    echo "  - Leave empty to start a new session."
    echo ""
    read -rp "Claude Code Session ID (optional): " session_id

    cat > "$CONFIG_FILE" << EOF
# NABU Configuration (generated by setup.sh)
CLAUDE_CHAT_URL="${chat_url}"
SESSION_ID="${session_id}"
EOF

    echo ""
    echo "✓ Config saved to $CONFIG_FILE"
fi

echo ""
echo "Installing scripts to /usr/local/bin ..."

NABU_WITH_CONFIG="$(mktemp)"
sed "s|NABU_CONFIG:-\$SCRIPT_DIR/config|NABU_CONFIG:-$CONFIG_FILE|" "$SCRIPT_DIR/nabu" > "$NABU_WITH_CONFIG"

if sudo cp "$NABU_WITH_CONFIG" /usr/local/bin/nabu && sudo chmod +x /usr/local/bin/nabu; then
    echo "✓ nabu → /usr/local/bin/nabu"
else
    echo "✗ Failed (need sudo)"
    rm -f "$NABU_WITH_CONFIG"
    exit 1
fi
rm -f "$NABU_WITH_CONFIG"

if sudo cp "$SCRIPT_DIR/worker" /usr/local/bin/nabu-worker && sudo chmod +x /usr/local/bin/nabu-worker; then
    echo "✓ worker → /usr/local/bin/nabu-worker"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Done!"
echo ""
echo "  nabu \"Hallo\""
echo "  nabu --health"
echo "  nabu --session"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
