#!/bin/bash
# NABU setup script
# Copies nabu and worker to /usr/local/bin and creates config

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  NABU Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# --- Config setup ---
if [ -f "$CONFIG_FILE" ]; then
    echo "✓ Config file already exists at $CONFIG_FILE"
    echo "  Delete it and re-run setup to reconfigure."
    echo ""
else
    echo "Creating config file..."
    echo ""

    read -rp "Home Assistant URL (e.g. http://192.168.1.225:8123): " ha_url
    read -rp "HA Long-lived Access Token: " ha_token
    read -rp "Conversation Agent ID: " agent_id
    read -rp "Default language [de]: " lang
    lang="${lang:-de}"

    cat > "$CONFIG_FILE" << EOF
# NABU Configuration (generated by setup.sh)
HA_URL="${ha_url}"
HA_TOKEN="${ha_token}"
AGENT_ID="${agent_id}"
DEFAULT_LANGUAGE="${lang}"
EOF

    echo ""
    echo "✓ Config saved to $CONFIG_FILE"
    echo "  (This file is git-ignored and stays local)"
fi

# --- Install scripts ---
echo ""
echo "Installing scripts to /usr/local/bin ..."

# nabu: inject config path so it's found regardless of cwd
NABU_WITH_CONFIG="$(mktemp)"
sed "s|NABU_CONFIG:-\$SCRIPT_DIR/config|NABU_CONFIG:-$CONFIG_FILE|" "$SCRIPT_DIR/nabu" > "$NABU_WITH_CONFIG"

if sudo cp "$NABU_WITH_CONFIG" /usr/local/bin/nabu && sudo chmod +x /usr/local/bin/nabu; then
    echo "✓ nabu → /usr/local/bin/nabu"
else
    echo "✗ Failed to install nabu (need sudo)"
    rm -f "$NABU_WITH_CONFIG"
    exit 1
fi
rm -f "$NABU_WITH_CONFIG"

if sudo cp "$SCRIPT_DIR/worker" /usr/local/bin/nabu-worker && sudo chmod +x /usr/local/bin/nabu-worker; then
    echo "✓ worker → /usr/local/bin/nabu-worker"
else
    echo "✗ Failed to install worker"
    exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Done! Try: nabu \"Hallo\""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
